# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0002_tldr_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tldr',
            new_name='Snip',
        ),
    ]
