# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0003_auto_20170420_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='is_locked',
            field=models.CharField(choices=[('LO', 'Locked'), ('FR', 'Free'), ('ND', 'Not decided')], null=True, max_length=2, verbose_name='Locked'),
        ),
    ]
