# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0004_snip_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='is_locked',
            field=models.CharField(choices=[('LO', 'Locked'), ('FR', 'Free')], max_length=2, verbose_name='Locked'),
        ),
    ]
