# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0006_anonlog_userlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='anonlog',
            name='param1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='param1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
