# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0007_auto_20170421_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonlog',
            name='param2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='param2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
