# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0011_auto_20170423_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Please add a date-time in the form YYYY-MM-DD hh:mm.', null=True, verbose_name='Publish date/time'),
        ),
        migrations.AddField(
            model_name='snip',
            name='tzone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York', verbose_name='Publish Timezone'),
        ),
    ]
