# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 15:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snips', '0012_auto_20170424_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='death_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 15, 28, 54, 555018, tzinfo=utc), help_text='Please add a date-time in the form YYYY-MM-DD hh:mm.', verbose_name='Post death date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='vote'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('snip', 'user')]),
        ),
    ]
