# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snips', '0013_auto_20170424_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('readmore', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('snip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snips.Snip')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('readmore', 'readmore'), ('share', 'share'), ('viewed', 'viewed')], max_length=15, verbose_name='action')),
                ('date', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='action')),
                ('snip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snips.Snip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='anonlog',
            name='action',
            field=models.CharField(choices=[('login', 'login'), ('readmore', 'readmore'), ('like', 'like'), ('dislike', 'dislike'), ('share', 'share'), ('viewed', 'viewed'), ('locked', 'locked')], max_length=15, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('login', 'login'), ('readmore', 'readmore'), ('like', 'like'), ('dislike', 'dislike'), ('share', 'share'), ('viewed', 'viewed'), ('locked', 'locked')], max_length=15, verbose_name='action'),
        ),
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together=set([('snip', 'user', 'action')]),
        ),
    ]
