# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import snips.models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0014_auto_20170424_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='comments_id',
            field=models.CharField(default=snips.models.generate_random_id, max_length=32),
        ),
    ]
