# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snips', '0016_auto_20170426_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSnipLog',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'login'), ('readmore', 'readmore'), ('like', 'like'), ('dislike', 'dislike'), ('share', 'share'), ('viewed', 'viewed'), ('locked', 'locked'), ('open_link', 'open_link')], max_length=15, verbose_name='action')),
                ('param1', models.CharField(blank=True, max_length=20, null=True)),
                ('param2', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(blank=True, editable=False, verbose_name='date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sessions.Session')),
                ('snip', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='snips.Snip')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical snip log',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='snip',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user',
        ),
        migrations.AddField(
            model_name='sniplog',
            name='snip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snips.Snip'),
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
