# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0017_auto_20170426_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetrics',
            name='open_link',
            field=models.IntegerField(default=0),
        ),
    ]
