# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0018_postmetrics_open_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmetrics',
            old_name='view',
            new_name='viewed',
        ),
    ]
