# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0019_auto_20170426_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referer',
            name='referer',
            field=models.CharField(max_length=500),
        ),
    ]
