# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0020_auto_20170426_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='death_factor',
            field=models.FloatField(default=0.85, verbose_name='Alpha value for death decay function'),
        ),
    ]
