# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0021_snip_death_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snip',
            old_name='image',
            new_name='image1',
        ),
    ]
