# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('snips', '0023_snip_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
