# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0024_snip_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontouser',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessiontouser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionToUser',
        ),
    ]
