# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0027_auto_20170502_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsniplog',
            name='action',
            field=models.CharField(choices=[('readmore', 'readmore'), ('like', 'like'), ('dislike', 'dislike'), ('share', 'share'), ('viewed', 'viewed'), ('locked', 'locked'), ('open_link', 'open_link')], max_length=15, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='sniplog',
            name='action',
            field=models.CharField(choices=[('readmore', 'readmore'), ('like', 'like'), ('dislike', 'dislike'), ('share', 'share'), ('viewed', 'viewed'), ('locked', 'locked'), ('open_link', 'open_link')], max_length=15, verbose_name='action'),
        ),
    ]
