# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0032_auto_20170508_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='snip',
            old_name='temp_category',
            new_name='category',
        ),
    ]
