# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0034_auto_20170509_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='post_on_twtr',
            field=models.BooleanField(default=False, verbose_name='Post on Twitter'),
        ),
        migrations.AddField(
            model_name='snip',
            name='twtr_post_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter ID'),
        ),
    ]
