# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0035_auto_20170511_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='fb_post_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook ID'),
        ),
        migrations.AddField(
            model_name='snip',
            name='post_on_fb',
            field=models.BooleanField(default=False, verbose_name='Post on Facebook'),
        ),
    ]
