# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snips', '0038_category_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='show_in_main',
            field=models.BooleanField(default=True, verbose_name='Show in Main Feed'),
        ),
    ]
