# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snips', '0041_snip_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snip',
            name='writer',
        ),
        migrations.AddField(
            model_name='snip',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
