# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0004_auto_20170502_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('action', models.CharField(choices=[('login', 'login'), ('signup', 'signup'), ('subscribe', 'subscribe')], max_length=15, verbose_name='action')),
                ('param1', models.CharField(blank=True, max_length=20, null=True)),
                ('param2', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
