# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20170508_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='param1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='param2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
